lib/ellie_web/router.ex
defmodule EllieWeb.Router do
  use EllieWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:put_secure_browser_headers, %{"x-frame-options" => "ALLOWALL"})
    plug(:put_layout, false)
    plug(EllieWeb.Plugs.Redirect)
  end

  pipeline :assets do
    plug(:accepts, ["javascript"])
  end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(EllieWeb.Graphql.Context)
  end

  pipeline :oembed do
    plug(:accepts, ["json"])
  end

  scope "/api" do
    pipe_through(:api)
    forward("/graphiql", Absinthe.Plug.GraphiQL, schema: EllieWeb.Graphql.Schema)
    forward("/", Absinthe.Plug, schema: EllieWeb.Graphql.Schema)
  end

  scope "/r" do
    pipe_through(:assets)
    get("/workspace", EllieWeb.ResultController, :workspace)
    get("/embed/:id", EllieWeb.ResultController, :embed)
  end

  scope "/oembed" do
    pipe_through(:oembed)
    get("/", EllieWeb.OembedController, :oembed)
  end

  scope "/" do
    get("/healthz", EllieWeb.HealthController, :healthz)

    pipe_through(:browser)

    # Need this in case a browser requests an old version and the server
    # doesn't have it
    get("/assets/*not_found", EllieWeb.PageController, :assets_fallback)

    get("/new", EllieWeb.PageController, :new_editor)

    get("/a/terms/:version", EllieWeb.PageController, :terms)

    get("/embed/:project_id/:revision_number", EllieWeb.PageController, :embed_old)
    get("/embed/:id", EllieWeb.PageController, :embed)
    get("/embed/*invalid", EllieWeb.PageController, :embed)

    get("/:project_id/:revision_number", EllieWeb.PageController, :existing_editor_old)
    get("/:id", EllieWeb.PageController, :existing_editor)

    get("/*path", EllieWeb.PageController, :new_editor)
  end
end

lib/ellie_web/templates/page/config.html.eex
<script>
    window.ellieConfig = {
        latestTerms: 4
    }
</script>

lib/ellie_web/templates/page/editor.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="public_path" content="<%= static_url(@conn, "/assets/") %>" />
    <link rel="icon" href="<%= static_url(@conn, "/assets/images/favicon.ico") %>" />
    <link rel="alternate" type="application/json+oembed" href="<%= oembed_url(@conn) %>" />
    <%= render("polyfills.html") %>
    <%= render("config.html", conn: @conn) %>
  </head>
  <body>
    <script src="<%= static_url(@conn, "/assets/editor.js") %>"></script>
  </body>
</html>

lib/ellie_web/templates/page/embed.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="public_path" content="<%= static_url(@conn, "/assets/") %>" />
    <link rel="icon" href="<%= static_url(@conn, "/assets/images/favicon.ico") %>" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
    <%= render("polyfills.html") %>
    <%= render("config.html", conn: @conn) %>
  </head>
  <body>
    <script src="<%= static_url(@conn, "/assets/embed.js") %>"></script>
  </body>
</html>

lib/ellie_web/templates/page/polyfills.html.eex
<script id="polyfills-loader">
    (function () {
        var currentScript = document.getElementById('polyfills-loader')

        // Promise
        if (typeof window.Promise === 'undefined') {
            var script1 = document.createElement('script')
            script1.src = '//cdn.jsdelivr.net/npm/es6-promise@4.2.4/dist/es6-promise.min.js'
            document.head.insertBefore(script1, currentScript.nextSibling)
            currentScript = script1
        }

        // RequestIdleCallback
        if (typeof window.requestIdleCallback === 'undefined') {
            var script2 = document.createElement('script')
            script2.src = '//cdn.jsdelivr.net/npm/request-idle-polyfill@1.0.1/dist/index.min.js'
            document.head.insertBefore(script2, currentScript.nextSibling)
            currentScript = script2
        }
    }())
</script>